//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snowinmars.Ui.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snowinmars.Ui.App_LocalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string _Author {
            get {
                return ResourceManager.GetString("_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string _BackToList {
            get {
                return ResourceManager.GetString("_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string _Book {
            get {
                return ResourceManager.GetString("_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string _Create {
            get {
                return ResourceManager.GetString("_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string _Go {
            get {
                return ResourceManager.GetString("_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string _Ok {
            get {
                return ResourceManager.GetString("_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string _Save {
            get {
                return ResourceManager.GetString("_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string _Sync {
            get {
                return ResourceManager.GetString("_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string _Users {
            get {
                return ResourceManager.GetString("_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are root.
        /// </summary>
        public static string _YouAreRoot {
            get {
                return ResourceManager.GetString("_YouAreRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yours.
        /// </summary>
        public static string _Yours {
            get {
                return ResourceManager.GetString("_Yours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most popular colloquial author&apos;s naming.
        /// </summary>
        public static string Author_ShortcutTooltip {
            get {
                return ResourceManager.GetString("Author_ShortcutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AuthorCreate_Header {
            get {
                return ResourceManager.GetString("AuthorCreate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AuthorDetails_Header {
            get {
                return ResourceManager.GetString("AuthorDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AuthorEdit_Header {
            get {
                return ResourceManager.GetString("AuthorEdit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new author.
        /// </summary>
        public static string AuthorIndex_CreateNewAuthor {
            get {
                return ResourceManager.GetString("AuthorIndex_CreateNewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All authors.
        /// </summary>
        public static string AuthorIndex_Header {
            get {
                return ResourceManager.GetString("AuthorIndex_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string AuthorModel_FamilyName {
            get {
                return ResourceManager.GetString("AuthorModel_FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full middle name.
        /// </summary>
        public static string AuthorModel_FullMiddleName {
            get {
                return ResourceManager.GetString("AuthorModel_FullMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        public static string AuthorModel_GivenName {
            get {
                return ResourceManager.GetString("AuthorModel_GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudonym family name.
        /// </summary>
        public static string AuthorModel_PseudonymFamilyName {
            get {
                return ResourceManager.GetString("AuthorModel_PseudonymFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudonym full middle name.
        /// </summary>
        public static string AuthorModel_PseudonymFullMiddleName {
            get {
                return ResourceManager.GetString("AuthorModel_PseudonymFullMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudonym given name.
        /// </summary>
        public static string AuthorModel_PseudonymGivenName {
            get {
                return ResourceManager.GetString("AuthorModel_PseudonymGivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string AuthorModel_Shortcut {
            get {
                return ResourceManager.GetString("AuthorModel_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save urls&apos; changes, push the Save button below.
        /// </summary>
        public static string Book_SaveUrlHint {
            get {
                return ResourceManager.GetString("Book_SaveUrlHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrokenDetails.
        /// </summary>
        public static string BookBroken_Header {
            get {
                return ResourceManager.GetString("BookBroken_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is broken, contact administrator..
        /// </summary>
        public static string BookBroken_Message {
            get {
                return ResourceManager.GetString("BookBroken_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BookCreate_Header {
            get {
                return ResourceManager.GetString("BookCreate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string BookDetails_Header {
            get {
                return ResourceManager.GetString("BookDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BookEdit_Header {
            get {
                return ResourceManager.GetString("BookEdit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new book.
        /// </summary>
        public static string BookIndex_CreateNewBook {
            get {
                return ResourceManager.GetString("BookIndex_CreateNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All books.
        /// </summary>
        public static string BookIndex_Header {
            get {
                return ResourceManager.GetString("BookIndex_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string BookModel_AdditionalInfo {
            get {
                return ResourceManager.GetString("BookModel_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string BookModel_Authors {
            get {
                return ResourceManager.GetString("BookModel_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookshelf.
        /// </summary>
        public static string BookModel_Bookshelf {
            get {
                return ResourceManager.GetString("BookModel_Bookshelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flibusta.
        /// </summary>
        public static string BookModel_FlibustaUrl {
            get {
                return ResourceManager.GetString("BookModel_FlibustaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibRusEc.
        /// </summary>
        public static string BookModel_LibRusEcUrl {
            get {
                return ResourceManager.GetString("BookModel_LibRusEcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveLib.
        /// </summary>
        public static string BookModel_LiveLibUrl {
            get {
                return ResourceManager.GetString("BookModel_LiveLibUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string BookModel_Owner {
            get {
                return ResourceManager.GetString("BookModel_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page count.
        /// </summary>
        public static string BookModel_PageCount {
            get {
                return ResourceManager.GetString("BookModel_PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BookModel_Title {
            get {
                return ResourceManager.GetString("BookModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string BookModel_Year {
            get {
                return ResourceManager.GetString("BookModel_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no such user with this name. Register then..
        /// </summary>
        public static string EnterPage_NewUserHello {
            get {
                return ResourceManager.GetString("EnterPage_NewUserHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s user with this login. Enter the password..
        /// </summary>
        public static string EnterPage_OldUserHello {
            get {
                return ResourceManager.GetString("EnterPage_OldUserHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banned..
        /// </summary>
        public static string HomeBanned_BannedMessage {
            get {
                return ResourceManager.GetString("HomeBanned_BannedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world.
        /// </summary>
        public static string HomeIndex_HelloMessage {
            get {
                return ResourceManager.GetString("HomeIndex_HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string Layout_AllUsers {
            get {
                return ResourceManager.GetString("Layout_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Layout_Enter {
            get {
                return ResourceManager.GetString("Layout_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library authors.
        /// </summary>
        public static string Layout_LibraryAuthors {
            get {
                return ResourceManager.GetString("Layout_LibraryAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library books.
        /// </summary>
        public static string Layout_LibraryBooks {
            get {
                return ResourceManager.GetString("Layout_LibraryBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal page.
        /// </summary>
        public static string Layout_PersonalPage {
            get {
                return ResourceManager.GetString("Layout_PersonalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to exit.
        /// </summary>
        public static string Layout_PressToExit {
            get {
                return ResourceManager.GetString("Layout_PressToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have I inform you about warnings?.
        /// </summary>
        public static string Model_InformAboutWarnings {
            get {
                return ResourceManager.GetString("Model_InformAboutWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is synchronized.
        /// </summary>
        public static string Model_IsSynchronized {
            get {
                return ResourceManager.GetString("Model_IsSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System can send you notification about your books&apos; unfinished specification and errors in book processing.
        ///You can&apos;t setup this notification now.
        ///You can erase this field any time..
        /// </summary>
        public static string UserDetails_EmailQuestionTooltip {
            get {
                return ResourceManager.GetString("UserDetails_EmailQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s wrong format.
        /// </summary>
        public static string UserDetails_IsWrongFormat {
            get {
                return ResourceManager.GetString("UserDetails_IsWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact root if you want more languages.
        /// </summary>
        public static string UserDetails_LanguageQuestionTooltip {
            get {
                return ResourceManager.GetString("UserDetails_LanguageQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal page:.
        /// </summary>
        public static string UserDetails_PersonalPage {
            get {
                return ResourceManager.GetString("UserDetails_PersonalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string UserDetails_Saved {
            get {
                return ResourceManager.GetString("UserDetails_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wasn&apos;t saved.
        /// </summary>
        public static string UserDetails_WasntSaved {
            get {
                return ResourceManager.GetString("UserDetails_WasntSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are.
        /// </summary>
        public static string UserDetails_YouAre {
            get {
                return ResourceManager.GetString("UserDetails_YouAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beware: actions can&apos;t be undone.
        /// </summary>
        public static string UserIndex_ActionCantBeDone {
            get {
                return ResourceManager.GetString("UserIndex_ActionCantBeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserModel_Email {
            get {
                return ResourceManager.GetString("UserModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UserModel_Language {
            get {
                return ResourceManager.GetString("UserModel_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserModel_Password {
            get {
                return ResourceManager.GetString("UserModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password сonfirm.
        /// </summary>
        public static string UserModel_PasswordConfirm {
            get {
                return ResourceManager.GetString("UserModel_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password aren&apos;t equals.
        /// </summary>
        public static string UserModel_PasswordConfirmError {
            get {
                return ResourceManager.GetString("UserModel_PasswordConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string UserModel_Roles {
            get {
                return ResourceManager.GetString("UserModel_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserModel_Username {
            get {
                return ResourceManager.GetString("UserModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We trust you have received the usual lecture from the local System Administrator.
        /// </summary>
        public static string UserRootPage_RootMessagePart1 {
            get {
                return ResourceManager.GetString("UserRootPage_RootMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It usually boils down to these three things:.
        /// </summary>
        public static string UserRootPage_RootMessagePart2 {
            get {
                return ResourceManager.GetString("UserRootPage_RootMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect the privacy of others.
        /// </summary>
        public static string UserRootPage_RootMessagePart3 {
            get {
                return ResourceManager.GetString("UserRootPage_RootMessagePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think before you type.
        /// </summary>
        public static string UserRootPage_RootMessagePart4 {
            get {
                return ResourceManager.GetString("UserRootPage_RootMessagePart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With great power comes great responsibility.
        /// </summary>
        public static string UserRootPage_RootMessagePart5 {
            get {
                return ResourceManager.GetString("UserRootPage_RootMessagePart5", resourceCulture);
            }
        }
    }
}
